[project]
authors = ["jknoxdev <techbiotic@posteo.de>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "getting-started"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.4.0,<25"
