---
- hosts: all
  tasks:
  - name: install packages
    become: true
    become_user: root
    apt:
      name:
        - htop
        - nload
        - mtr
        - ufw
        - neofetch
      state: latest
      
